apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-vijay-umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vijaykankane/shopNow-E2E'
    targetRevision: HEAD
    path: kubernetes/argocd/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vijay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
