apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/vijaykankane/shopNow-E2E'
    targetRevision: HEAD
    path: kubernetes/helm/charts/mongo
    helm:
      valueFiles: []
      releaseName: mongo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vijay
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
