apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: vijay
type: Opaque
stringData:
  MONGODB_URI: mongodb://shopuser:ShopNowPass123@mongo-0.mongo-headless.vijay.svc.cluster.local:27017/shopnow?authSource=admin
